# Generated by Django 2.2.3 on 2019-07-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(blank=True, max_length=30, null=True)),
                ('jobtype', models.CharField(blank=True, max_length=20, null=True)),
                ('pubtime', models.CharField(blank=True, max_length=20, null=True)),
                ('neednum', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('cptype', models.TextField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'jobinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
